apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat-api
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: soat-api
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m" 