apiVersion: apps/v1
kind: Deployment
metadata:
  name: soat-api
  namespace: soat-api-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: soat-api
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: NODE_ENV
          value: "development"
        - name: LOG_LEVEL
          value: "debug" 