apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: soat-api-dev

resources:
- ../../base

# patchesStrategicMerge:
# - deployment-patch.yaml
# - configmap-patch.yaml

configMapGenerator:
- name: soat-api-config
  behavior: create
  literals:
  - NODE_ENV=development
  - LOG_LEVEL=debug
  - API_BASE_URL=https://dev-api.soat.com

secretGenerator:
- name: soat-api-secrets
  behavior: create
  literals:
  - DB_PASSWORD=dev-password
  - MERCADO_PAGO_ACCESS_TOKEN=TEST-DEV-TOKEN

commonLabels:
  environment: development
  tier: development

images:
- name: soat-api
  newTag: dev-latest 