apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: soat-api-base

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- ingress.yaml
- pdb.yaml
- network-policy.yaml

commonLabels:
  app: soat-api
  version: v1.0.0
  environment: base 