#!/bin/bash

# Script to help set up GitHub repository secrets for CI/CD
# Run this script to get the commands needed to set up secrets in GitHub

echo "🔐 Setting up GitHub Repository Secrets for SOAT API CI/CD"
echo "=================================================="
echo ""
echo "You need to add the following secrets to your GitHub repository:"
echo ""
echo "1. Go to your GitHub repository: https://github.com/YOUR_USERNAME/YOUR_REPO"
echo "2. Click on 'Settings' tab"
echo "3. Click on 'Secrets and variables' → 'Actions'"
echo "4. Click 'New repository secret' for each of the following:"
echo ""

echo "📋 Required Secrets:"
echo "==================="
echo ""
echo "Secret Name: AWS_ACCESS_KEY_ID"
echo "Secret Value: YOUR_AWS_ACCESS_KEY_ID"
echo ""
echo "Secret Name: AWS_SECRET_ACCESS_KEY"
echo "Secret Value: YOUR_AWS_SECRET_ACCESS_KEY"
echo ""
echo "🔧 Optional Secrets (for enhanced security):"
echo "==========================================="
echo ""
echo "Secret Name: ECR_REGISTRY"
echo "Secret Value: 444162776953.dkr.ecr.us-east-1.amazonaws.com"
echo ""
echo "Secret Name: EKS_CLUSTER_NAME"
echo "Secret Value: soat-dev-cluster"
echo ""
echo "Secret Name: AWS_REGION"
echo "Secret Value: us-east-1"
echo ""

echo "🚀 After setting up secrets, your CI/CD pipeline will:"
echo "====================================================="
echo "✅ Run tests on every PR"
echo "✅ Build and push Docker image on merge to main"
echo "✅ Deploy to AWS EKS automatically"
echo "✅ Run security scans"
echo "✅ Verify deployment health"
echo ""

echo "📝 Next Steps:"
echo "============="
echo "1. Set up the secrets above in GitHub"
echo "2. Push this code to your GitHub repository"
echo "3. Create a PR to test the pipeline"
echo "4. Merge to main to trigger deployment"
echo ""

echo "🔍 To test the pipeline:"
echo "======================="
echo "1. Make a small change to soat-api/src/"
echo "2. Commit and push to a feature branch"
echo "3. Create a PR to main"
echo "4. Check the 'Actions' tab in GitHub to see the pipeline running"
echo "5. Merge the PR to trigger deployment"
echo ""

echo "✅ Setup complete! Your CI/CD pipeline is ready to go!"
